<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; Testing Hypothesis 2: ANOVA and Linear Regression – Qualitative and Quantitative Research Methods in Psychology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./r_4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./r_5.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Testing Hypothesis 2: ANOVA and Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Qualitative and Quantitative Research Methods in Psychology</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Sample</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data and types of scales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normdist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Normal distribution and standardization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction to Data Analysis in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data preprocessing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualizations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistical inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./criteria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Statistical criteria</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./group_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Comparison of group averages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Checking the linear link</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Testing hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r_5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Testing Hypothesis 2: ANOVA and Linear Regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#anova-analysis-of-variance" id="toc-anova-analysis-of-variance" class="nav-link active" data-scroll-target="#anova-analysis-of-variance"><span class="header-section-number">14.0.1</span> ANOVA (analysis of variance)</a></li>
  <li><a href="#reshaping" id="toc-reshaping" class="nav-link" data-scroll-target="#reshaping"><span class="header-section-number">14.0.2</span> 14.13.2 Reshaping</a></li>
  <li><a href="#assignments-after-the-seminar-6" id="toc-assignments-after-the-seminar-6" class="nav-link" data-scroll-target="#assignments-after-the-seminar-6"><span class="header-section-number">14.1</span> 14.14 Assignments after the seminar 6</a></li>
  <li><a href="#linear-regression-analysis" id="toc-linear-regression-analysis" class="nav-link" data-scroll-target="#linear-regression-analysis"><span class="header-section-number">14.2</span> 14.15 Linear Regression Analysis</a>
  <ul class="collapse">
  <li><a href="#linear-regression-with-one-predictor-factor" id="toc-linear-regression-with-one-predictor-factor" class="nav-link" data-scroll-target="#linear-regression-with-one-predictor-factor"><span class="header-section-number">14.2.1</span> 14.15.1 Linear Regression with One Predictor (Factor)</a></li>
  <li><a href="#linear-regression-with-multiple-predictors-factors" id="toc-linear-regression-with-multiple-predictors-factors" class="nav-link" data-scroll-target="#linear-regression-with-multiple-predictors-factors"><span class="header-section-number">14.2.2</span> 14.15.2 Linear Regression with Multiple Predictors (Factors)</a></li>
  </ul></li>
  <li><a href="#assignments-after-the-seminar-7" id="toc-assignments-after-the-seminar-7" class="nav-link" data-scroll-target="#assignments-after-the-seminar-7"><span class="header-section-number">14.3</span> 14.16 Assignments after the seminar 7</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">14.4</span> 14.17 Logistic Regression</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Testing Hypothesis 2: ANOVA and Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="anova-analysis-of-variance" class="level3" data-number="14.0.1">
<h3 data-number="14.0.1" class="anchored" data-anchor-id="anova-analysis-of-variance"><span class="header-section-number">14.0.1</span> ANOVA (analysis of variance)</h3>
<p>I wanted to add some variety to our data, so I found another <a href="https://elenary.github.io/StatsForDA/R_analysis.html#https://github.com/elenary/StatsForDA/blob/main/Chapter2OnlineData2019.xls?raw=true">table</a> related to the World Happiness Report, you can read more about it <a href="https://elenary.github.io/StatsForDA/R_analysis.html#https://s3.amazonaws.com/happiness-report/2019/WHR19_Ch2A_Appendix1.pdf">here</a> (by the way, this doc, apparently, is also formatted in R).</p>
<p>This is roughly what preprocessing of real (not the cleanest and crooked) data might look like: I combine two tables (the table for 2016 and the new table for 2019) using the function <code>right_join</code>(this means that I attach the left table to the right one, and everything that is left in the left one that does not fit into the right one is not taken) from the family <code>join</code>, rename columns and replace spaces on them with underscores using the function <code>rename_with</code>, select only the columns that interest me using the function <code>select</code>, create new variables that we have already created earlier in homework, using the mutate function and save the result in a new table in the dataset<code>whr_tests_hw</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>whr_2019 <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_xls</span>(<span class="st">"Chapter2OnlineData2019.xls"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>whr <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"2016.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>whr_2019 <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> <span class="fu">gsub</span>(<span class="st">" "</span>, <span class="st">"_"</span>, .), <span class="at">.cols =</span> <span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country_name<span class="sc">:</span>Negative_affect) <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">&lt;=</span> <span class="dv">2016</span>) <span class="ot">-&gt;</span> whr_2019</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>whr <span class="sc">%&gt;%</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> <span class="fu">gsub</span>(<span class="st">" "</span>, <span class="st">"_"</span>, .), <span class="at">.cols =</span> <span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country, Happiness_Rank, Happiness_Score) <span class="sc">%&gt;%</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(whr_2019, <span class="at">by =</span> <span class="fu">join_by</span>(Country <span class="sc">==</span> Country_name), <span class="at">multiple =</span> <span class="st">"last"</span>) <span class="ot">-&gt;</span> tmp</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>whr <span class="sc">%&gt;%</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Country<span class="sc">:</span>Region) <span class="sc">%&gt;%</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(tmp, <span class="at">by =</span> <span class="fu">join_by</span>(Country <span class="sc">==</span> Country), <span class="at">multiple =</span> <span class="st">"all"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"top20"</span> <span class="ot">=</span> <span class="fu">ifelse</span>(Happiness_Rank<span class="sc">&lt;=</span><span class="dv">20</span>, <span class="st">"hehe"</span>, <span class="st">"not hehe"</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>         <span class="st">"mean_position"</span> <span class="ot">=</span> <span class="fu">ifelse</span>(Happiness_Score<span class="sc">&gt;=</span> <span class="fu">mean</span>(Happiness_Score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="st">"upper"</span>, <span class="st">"lower"</span>)) <span class="ot">-&gt;</span> whr_tests_hw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I also downloaded the result of this preprocessing into a separate file using <code>R</code>the function <a href="https://raw.githubusercontent.com/elenary/StatsForDA/main/whr_tests_hw.csv" class="uri">https://raw.githubusercontent.com/elenary/StatsForDA/main/whr_tests_hw.csv</a><code>write_csv()</code></p>
<p>Previously, we tested the hypothesis that the Happiness Score differs in two regions: Western and Eastern and Central Europe. But what if I want to check whether the level of happiness differs statistically significantly in three regions - Western and Eastern and Central Europe and in Latin America? Again, we turn to <a href="https://elenary.github.io/StatsForDA/stats_criteria.html#stats_criteria">the statistical criteria</a> we studied last semester , remember the picture with the tree of choosing statistical tests <a href="https://miro.com/app/board/uXjVOxmKhr8=/" class="uri">https://miro.com/app/board/uXjVOxmKhr8=/</a> . If we have a quantitative PP, categorical NP / categorical, and we need to conduct 3 or more comparisons - then we move from the t-test to <a href="https://elenary.github.io/StatsForDA/stats_criteria_ttest_anova.html#anova">ANOVA (analysis of variance)</a> .</p>
<p>I will periodically adhere to the form of writing code when I do everything at once inside one pipe - both filtering and plotting graphs or calculating a test, but do not forget that before writing everything together, you need to make sure that each line works. And it may be more convenient at first to create more variables and write the filtering results there, and then use this variable - this will make it easier to debug the code. For example, you can first filter the data and write it to a new dataset (sometimes it happens that you cannot do without this form of writing)</p>
<pre><code>whr_tests_hw %&gt;%
  filter(Region == "Central and Eastern Europe" | Region == "Western Europe" | Region == "Latin America and Caribbean") %&gt;%
  filter(Year == "2016") -&gt; whr_anova</code></pre>
<p>Recalling the assumptions for <a href="https://elenary.github.io/StatsForDA/stats_criteria_ttest_anova.html#anova">ANOVA</a></p>
<p>First, wages should be distributed close to a normal distribution.</p>
<pre><code>whr_anova %&gt;%
  ggplot(aes(x = Happiness_Score)) +
  geom_density(color = "#355C7D") +
  theme_minimal()</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid"></p>
<pre><code>whr_anova %&gt;%
  ggplot(aes(sample = Happiness_Score)) +
  stat_qq(color = "#355C7D") +
  geom_qq_line() +
  theme_minimal()</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-65-2.png" class="img-fluid"></p>
<p>Let’s say it looks like a normal distribution.</p>
<p>The second assumption is homogeneity (homoscedasticity) of variances. Variances should be the same in our groups. If they are different, this is bad, and we will have to use nonparametric analogs of ANOVA. Homogeneity of variances is checked using Levene’s Test. Note: here we are interested in obtaining a NON-significant result - because if the test yielded a significant result, then the variances in the groups are different, and this is not ok. We will need a function <code>leveneTest</code>from the package<code>car</code></p>
<pre><code>options(scipen = 999) # 

# install.packages("car")
library(car)
leveneTest(Happiness_Score ~ Region, data = whr_anova)</code></pre>
<pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.</code></pre>
<pre><code>## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  2  0.7143 0.4933
##       66</code></pre>
<p>Look at the p-value: it’s not significant, hooray! So we’ve met all the assumptions, and we can safely use anova. We’ll try to build it in two ways: using a standard function <code>aov</code>and using a function <code>ezANOVA</code>from a package <code>ez</code>with a clearer syntax, but more picky and less stable.</p>
<pre><code>aov_model1 &lt;- aov(Happiness_Score ~ Region, data = whr_anova) #выполняем АНОВУ
summary(aov_model1) #выводим табличку АНОВЫ</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value       Pr(&gt;F)    
## Region       2  21.40  10.698   21.37 0.0000000697 ***
## Residuals   66  33.04   0.501                         
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>How to interpret these results? The first thing we look at is the p-value (column Pr(F)). If it is less than the set levelaa, then we say that <em>we reject the null hypothesis and we have obtained statistically significant differences</em> . If the p-value is greater than or equal toaa– <em>we do not have enough evidence to support the alternative hypothesis, and we say that we do not reject the null hypothesis</em> .</p>
<p>The second option for constructing the same analysis using the function <code>ezANOVA.</code>She, by the way, immediately does Levene’s test, so we have two outputs.</p>
<pre><code># install.packages("ez")
library(ez)

whr_anova %&gt;% 
  ezANOVA(., Happiness_Score, wid = Country, between = Region)</code></pre>
<pre><code>## Warning: Converting "Country" to factor for ANOVA.</code></pre>
<pre><code>## Warning: Converting "Region" to factor for ANOVA.</code></pre>
<pre><code>## Warning: Data is unbalanced (unequal N per group). Make sure you specified a
## well-considered value for the type argument to ezANOVA().</code></pre>
<pre><code>## $ANOVA
##   Effect DFn DFd        F              p p&lt;.05       ges
## 1 Region   2  66 21.37266 0.000000069727     * 0.3930773
## 
## $`Levene's Test for Homogeneity of Variance`
##   DFn DFd       SSn      SSd         F         p p&lt;.05
## 1   2  66 0.3066018 14.16483 0.7142945 0.4932823</code></pre>
<p>If we compare the results, they will be exactly the same, only the second function in the ges column also gives the effect size! This is eta squaredor2or2, <a href="https://elenary.github.io/StatsForDA/inference.html#sample_size">the effect size metric for ANOVA</a> , which you used anyway in your homework last year. We can see that the effect we got is quite large!</p>
<p>We can calculate it separately for the previous table using the package function effectsize</p>
<pre><code># install.packages("effectsize")
library(effectsize)

eta_squared(aov_model1)</code></pre>
<pre><code>## # Effect Size for ANOVA
## 
## Parameter | Eta2 |       95% CI
## -------------------------------
## Region    | 0.39 | [0.24, 1.00]
## 
## - One-sided CIs: upper bound fixed at [1.00].</code></pre>
<p>The value will be the same as in the ges column of the ezANOVA output.</p>
<p>Visualize the results. The most common methods for visualizing ANOVA are boxplots or violet plots.</p>
<pre><code>whr_anova %&gt;%
  ggplot(aes(x=Region, y = Happiness_Score, fill = Region)) +
  geom_boxplot() +
  theme_minimal() +
  scale_fill_manual(values = wes_palette("FantasticFox1"))</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-70-1.png" class="img-fluid"> Or you can often find graphs that only show averages</p>
<pre><code>whr_anova %&gt;%
  ggplot(aes(x=Region, y = Happiness_Score, color = Region, group = 1)) +
  stat_summary(fun = mean, geom = 'point') +
  stat_summary(fun = mean, geom = 'line') +
  stat_summary(fun.data = mean_cl_boot, geom = 'errorbar') +
  theme_minimal() +
  scale_color_manual(values = wes_palette("FantasticFox1"))</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid"></p>
<p>We know that the ANOVA is significant, that is, there are statistically significant differences between the three regions. But how do we know which regions are contributing to the significance? Could it be that the significance is being provided by one region that is very different from the others, while the other two are not different? It is. To find out, we need to conduct <a href="https://elenary.github.io/StatsForDA/R_analysis.html#id_%D0%BF%D0%BE%D1%81%D1%82-%D1%85%D0%BE%D0%BA%D0%B8-%D0%B8-%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F">post-hoc tests</a> .</p>
<section id="post-hoc-analysis" class="level4" data-number="14.0.1.1">
<h4 data-number="14.0.1.1" class="anchored" data-anchor-id="post-hoc-analysis"><span class="header-section-number">14.0.1.1</span> 14.13.1.1 Post-hoc analysis</h4>
<p>Post hocs are pairwise multiple comparisons of everything with everything. Remember that when we do this, we risk getting a statistically significant result purely by chance, because the probability of a type I error increases greatly, and corrections for multiple comparisons are needed. You can do post hoc analysis, for example, using built-in functions <code>TukeyHSD</code>or<code>pairwise.t.test</code></p>
<pre><code>TukeyHSD(aov_model1, conf.level=.95)</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Happiness_Score ~ Region, data = whr_anova)
## 
## $Region
##                                                             diff        lwr
## Latin America and Caribbean-Central and Eastern Europe 0.7082577 0.20757381
## Western Europe-Central and Eastern Europe              1.3149770 0.82891110
## Western Europe-Latin America and Caribbean             0.6067193 0.06961039
##                                                             upr     p adj
## Latin America and Caribbean-Central and Eastern Europe 1.208942 0.0033334
## Western Europe-Central and Eastern Europe              1.801043 0.0000000
## Western Europe-Latin America and Caribbean             1.143828 0.0230915</code></pre>
<pre><code>pairwise.t.test(whr_anova$Happiness_Score, whr_anova$Region, p.adj = "bonf")</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  whr_anova$Happiness_Score and whr_anova$Region 
## 
##                             Central and Eastern Europe
## Latin America and Caribbean 0.0035                    
## Western Europe              0.000000039               
##                             Latin America and Caribbean
## Latin America and Caribbean -                          
## Western Europe              0.0258                     
## 
## P value adjustment method: bonferroni</code></pre>
</section>
<section id="nonparametric-analogues-of-anova" class="level4" data-number="14.0.1.2">
<h4 data-number="14.0.1.2" class="anchored" data-anchor-id="nonparametric-analogues-of-anova"><span class="header-section-number">14.0.1.2</span> 14.13.1.2 Nonparametric Analogues of ANOVA</h4>
<p>If our variable has significant outliers, fails the normality test, and the variances in the groups are statistically significantly different, then we cannot use ANOVA. What to do? Conduct an analogue of ANOVA, the Kruskal-Wallis test. I will show it on the same data that we took for ANOVA, where we looked at different levels of happiness by region.</p>
<pre><code>kruskal.test(Happiness_Score ~ Region, data = whr_anova)</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Happiness_Score by Region
## Kruskal-Wallis chi-squared = 26.36, df = 2, p-value = 0.000001888</code></pre>
</section>
<section id="multivariate-anova" class="level4" data-number="14.0.1.3">
<h4 data-number="14.0.1.3" class="anchored" data-anchor-id="multivariate-anova"><span class="header-section-number">14.0.1.3</span> 14.13.1.3 Multivariate ANOVA</h4>
<p>We tested the hypothesis with only one NP - region. But what if my hypothesis concerns several factors? For example, I want to test the hypothesis that the variable <code>Life_Ladder</code>(analogous to <code>Happiness Score</code>, shows the survey results, where respondents are by level of happiness in the form of a ladder with 10 steps) is affected by both region and year.</p>
<p>I’ll go back to the original dataset and remove the year filtering.</p>
<p>It’s all the same - let’s check the assumptions first.</p>
<pre><code>whr_tests_hw %&gt;%
  filter(Region == "Central and Eastern Europe" | 
           Region == "Western Europe" | 
           Region == "Latin America and Caribbean") %&gt;%
  ggplot(aes(x = Life_Ladder)) +
  geom_density(color = "#355C7D") +
  theme_minimal()</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-74-1.png" class="img-fluid"></p>
<pre><code>whr_tests_hw %&gt;%
  filter(Region == "Central and Eastern Europe" | 
           Region == "Western Europe" | 
           Region == "Latin America and Caribbean") %&gt;%
  ggplot(aes(sample = Life_Ladder)) +
  stat_qq(color = "#355C7D") +
  geom_qq_line() +
  theme_minimal()</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-74-2.png" class="img-fluid"></p>
<pre><code>whr_tests_hw %&gt;%
  filter(Region == "Central and Eastern Europe" | 
           Region == "Western Europe" | 
           Region == "Latin America and Caribbean") %&gt;%
  aov(Life_Ladder ~ Region + as.factor(Year), data = .) -&gt; aov_model3
#на всякий случай сделала as.factor(), он просто превращает число в строку. функции бывают не очень умными и думают, что нужнобрать числовую переменную 
# как число, даже если задаем ее как группирующую переменную (фактор)
summary(aov_model3)</code></pre>
<pre><code>##                  Df Sum Sq Mean Sq F value              Pr(&gt;F)    
## Region            2  273.0  136.51 271.048 &lt;0.0000000000000002 ***
## as.factor(Year)  11    6.8    0.62   1.229               0.263    
## Residuals       681  343.0    0.50                                
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>The formula of the entry <code>dependent var ~ independen var 1 + independent var 2</code> means that I take into account two factors independently of each other. But sometimes I am interested in the interaction of factors: maybe in some regions nothing has changed much over the years, the level of happiness measured as <code>Life_Ladder</code>was constant, and in some regions there was a huge increase (or a huge negative increase) in the level of happiness? Then I will need to check the interaction of factors, and the formula will be: <code>dependent var ~ independen var 1 * independent var 2</code> Wherever I am interested in interaction, I put an asterisk instead of a plus.</p>
<pre><code>whr_tests_hw %&gt;%
  filter(Region == "Central and Eastern Europe" | 
           Region == "Western Europe" | 
           Region == "Latin America and Caribbean") %&gt;%
  aov(Life_Ladder ~ Region * as.factor(Year), data = .) -&gt; aov_model4
summary(aov_model4)</code></pre>
<pre><code>##                         Df Sum Sq Mean Sq F value              Pr(&gt;F)    
## Region                   2  273.0  136.51 274.254 &lt;0.0000000000000002 ***
## as.factor(Year)         11    6.8    0.62   1.244               0.254    
## Region:as.factor(Year)  22   15.0    0.68   1.366               0.123    
## Residuals              659  328.0    0.50                                
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>We see that in the second case we have another line – Region:Year. This is precisely the interaction of two factors. And it is, by the way, significant! That is, the assumption that different regions have different dynamics of changes in the level of happiness by year is correct.</p>
<p>Next, to determine what exactly was significant, we do post-hocs.</p>
<pre><code>TukeyHSD(aov_model3, conf.level=.95)
TukeyHSD(aov_model4, conf.level=.95)</code></pre>
<p>I won’t draw a table – it turns out to be monstrous because we took the years, and they start from 2005: imagine how many pairwise comparisons there are…</p>
</section>
<section id="repeated-measures-anova" class="level4" data-number="14.0.1.4">
<h4 data-number="14.0.1.4" class="anchored" data-anchor-id="repeated-measures-anova"><span class="header-section-number">14.0.1.4</span> 14.13.1.4 Repeated Measures ANOVA</h4>
<p>Actually, the year variable is a within-group factor. And to be honest, it is not very good to take it into account in the same way as the Region factor, otherwise we will lose a lot of information. In R, ANOVA with repeated measures can be done by specifying additional parameters in the aov() function, or with the already familiar ezANOVA() function, or with the very similar anova_test() function.</p>
<pre><code>whr_tests_hw %&gt;%
  filter(Region == "Central and Eastern Europe" | 
           Region == "Western Europe" | 
           Region == "Latin America and Caribbean") %&gt;%
  filter(Year &gt; 2010) %&gt;% #возьму года после 2010, чтобы было поменьше
  drop_na(Life_Ladder, Year) %&gt;% #удаляю пропущенные значения в интересующих меня колонках
  aov(Life_Ladder ~ Year + Error(Country/Year), .) %&gt;%
  summary()</code></pre>
<pre><code>## Warning in aov(Life_Ladder ~ Year + Error(Country/Year), .): Error() model is
## singular</code></pre>
<pre><code>## 
## Error: Country
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Year       1   8.94   8.935   2.095  0.152
## Residuals 71 302.81   4.265               
## 
## Error: Country:Year
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Year       1  0.003  0.0027    0.01  0.919
## Residuals 70 18.106  0.2586               
## 
## Error: Within
##            Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals 270  12.92 0.04784</code></pre>
<p>How to set this formula: If a factor appears several times for the same subject or country in this case, then the formula for writing it will be as follows <code>dependent var ~ independen var + Error(ID/independen var)</code></p>
<p>The anova_test function has a more human syntax, but it is very sensitive to data, and for example, it was not built on these data. <em>Later I realized why: I forgot to check for the identity of the variances, so the model does not converge! But I am too lazy to rewrite it.</em></p>
<pre><code>whr_tests_hw %&gt;%
  filter(Region == "Central and Eastern Europe" | 
           Region == "Western Europe" | 
           Region == "Latin America and Caribbean") %&gt;%
  filter(Year &gt; 2010) %&gt;%
  drop_na(Life_Ladder, Year) %&gt;% 
  ezANOVA(., dv = Life_Ladder, wid = Country, within = as.factor(Year))</code></pre>
</section>
</section>
<section id="reshaping" class="level3" data-number="14.0.2">
<h3 data-number="14.0.2" class="anchored" data-anchor-id="reshaping"><span class="header-section-number">14.0.2</span> 14.13.2 Reshaping</h3>
<p>Sometimes, for repeated measures tests, some functions accept data in a different format as input. For example, this is exactly what happened in Jamovi. Notice how our repeated measures data looks now: we have a column <code>Year</code>that lists the years, and a column <code>Life_Ladder</code>that lists the values ​​corresponding to those years.</p>
<pre><code>whr_tests_hw %&gt;% 
  select(Country, Year, Life_Ladder) %&gt;% 
  filter(Year&gt;2010) %&gt;% 
  head() #выводит заголовок таблички, первые 10 строк</code></pre>
<pre><code>## # A tibble: 6 × 3
##   Country  Year Life_Ladder
##   &lt;chr&gt;   &lt;dbl&gt;       &lt;dbl&gt;
## 1 Denmark  2016        7.56
## 2 Denmark  2011        7.79
## 3 Denmark  2012        7.52
## 4 Denmark  2013        7.59
## 5 Denmark  2014        7.51
## 6 Denmark  2015        7.51</code></pre>
<p>This data format is called <em>long</em> (no joke, that’s what it’s called!) because the data is stretched out in length, instead of each row consisting of unique data (pay attention to the column <code>Country</code>- there are repeating values ​​there, because we have many measurements in different years for each country). Sometimes it is necessary to convert the data to <em>a wide</em> format - so that the values ​​in the rows do not repeat, but instead of two columns, we have a column with measurements <code>Life_Ladder</code>for each year. This transformation is called data reshaping, as if changing their shape. You can convert the data type from long to wide format or back using the pivot_wider pivot_longer functions. Unfortunately, reshaping is not implemented in Jamovi.</p>
<pre><code>whr_tests_hw %&gt;% 
  select(Country, Year, Life_Ladder) %&gt;% 
  filter(Year&gt;2010) %&gt;% 
  pivot_wider(names_from = Year, values_from = Life_Ladder) %&gt;% 
  head()</code></pre>
<pre><code>## # A tibble: 6 × 7
##   Country     `2016` `2011` `2012` `2013` `2014` `2015`
##   &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Denmark       7.56   7.79   7.52   7.59   7.51   7.51
## 2 Switzerland   7.46  NA      7.78  NA      7.49   7.57
## 3 Iceland       7.51  NA      7.59   7.50  NA      7.50
## 4 Norway        7.60  NA      7.68  NA      7.44   7.60
## 5 Finland       7.66   7.35   7.42   7.44   7.38   7.45
## 6 Canada        7.24   7.43   7.42   7.59   7.30   7.41</code></pre>
</section>
<section id="assignments-after-the-seminar-6" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="assignments-after-the-seminar-6"><span class="header-section-number">14.1</span> 14.14 Assignments after the seminar 6</h2>
<p>Test several hypotheses on the dataset <code>whr_tests_hw</code>using ANOVA and linear regression analysis: select variables suitable for these tests, formulate a hypothesis, formulateH0H0AndH1H1, select levelaa, (if necessary, preprocess the data), check the assumptions for the tests.</p>
<ol type="1">
<li><p>Select appropriate variables, formulate a meaningful hypothesis, and test it using one-way ANOVA. Interpret the results: was the hypothesis confirmed?</p></li>
<li><p>Select appropriate variables, formulate a meaningful hypothesis and test it with a multivariate ANOVA. Interpret the results: was the hypothesis confirmed?</p></li>
<li><p>Select appropriate variables, formulate a meaningful hypothesis, and test it using repeated measures ANOVA. Interpret the results: was the hypothesis supported?</p></li>
<li><p>Conduct the same tests of hypotheses 1-3 using linear regression analysis.</p></li>
</ol>
</section>
<section id="linear-regression-analysis" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="linear-regression-analysis"><span class="header-section-number">14.2</span> 14.15 Linear Regression Analysis</h2>
<p>Now let’s move on to one of the most important methods in data analysis, including psychological ones - <a href="https://elenary.github.io/StatsForDA/stats_criteria_linear.html#linreg">linear regression</a> . First of all, we need to remember when this method is used - and it is used when both the PP and the NP are quantitative. When we talked about correlations, we discussed that this is a simplified version of linear regression, when we have only one NP. For one NP, we can do both a correlation test and a regression analysis, but when there are two or more quantitative NPs, we only need regression. We also discussed that ANOVA is actually a subtype of linear regression, if we move from quantitative NPs to categorical ones! But first things first, let’s start with quantitative NPs, a more classic case of linear regression.</p>
<p>Before we build a regression model, we need to check <a href="https://elenary.github.io/StatsForDA/stats_criteria_linear.html#assumptions_linreg">the assumptions for linear regression</a></p>
<p>Note that we are not so interested in how normally the salaries are distributed! This is the power of linear regression, that it is robust to salaries of different distributions. But another assumption regarding the distribution of data by salaries is the linearity between the NP and the salaries on which we want to build the model, we need to make sure that there is a linear relationship between them (and not a hole in a donut or a gnome-shaped entity). This is the first assumption.</p>
<p>I chose for analysis the hypothesis that the level of happiness according to the subjective position on the ladder <code>Life_Ladder</code>depends on the parameters <code>Log_GDP_per_capita</code>(purchasing power, GDP per capita), <code>Social_support</code>, <code>Freedom_to_make_life_choices</code>,<code>Perceptions_of_corruption.</code></p>
<p>Let’s test the assumption of a linear relationship between Life_Ladder salary and several potential variables that I have selected for analysis.</p>
<pre><code>whr_tests_hw %&gt;% 
  ggplot(aes(x = Log_GDP_per_capita, y = Life_Ladder)) +
  geom_point(color = "#355C7D", size = 1) +
  theme_minimal()</code></pre>
<pre><code>## Warning: Removed 15 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-82-1.png" class="img-fluid"></p>
<pre><code>whr_tests_hw %&gt;% 
  ggplot(aes(x = Social_support, y = Life_Ladder)) +
  geom_point(color = "#355C7D", size = 1) +
  theme_minimal()</code></pre>
<pre><code>## Warning: Removed 12 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-82-2.png" class="img-fluid"></p>
<pre><code>whr_tests_hw %&gt;% 
  ggplot(aes(x = Freedom_to_make_life_choices, y = Life_Ladder)) +
  geom_point(color = "#355C7D", size = 1) +
  theme_minimal()</code></pre>
<pre><code>## Warning: Removed 28 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-82-3.png" class="img-fluid"></p>
<pre><code>whr_tests_hw %&gt;% 
  ggplot(aes(x = Perceptions_of_corruption, y = Life_Ladder)) +
  geom_point(color = "#355C7D", size = 1) +
  theme_minimal()</code></pre>
<pre><code>## Warning: Removed 78 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-82-4.png" class="img-fluid"></p>
<p>I see that the Log_GDP_per_capita variable shows a very good linear relationship, the Freedom_to_make_life_choices variable is close to this. I don’t really like the Social_support variable, but I can try to transform it in the process, but the Perceptions_of_corruption variable looks frankly bad, I’ll take it as an anti-example.</p>
<section id="linear-regression-with-one-predictor-factor" class="level3" data-number="14.2.1">
<h3 data-number="14.2.1" class="anchored" data-anchor-id="linear-regression-with-one-predictor-factor"><span class="header-section-number">14.2.1</span> 14.15.1 Linear Regression with One Predictor (Factor)</h3>
<p>I will build a model with one factor to begin with – Log_GDP_per_capita. The model is built using the lm() function, to display the main information about the model you need to display summary(). By the way, you can also display these results immediately as ANOVA – this is all because, in fact, this is a subspecies of the same linear regression, and if we like the ANOVA table, we can get it by simply applying the functions to the anova() model</p>
<pre><code>whr_tests_hw %&gt;% 
  lm(Life_Ladder ~ Log_GDP_per_capita, .) -&gt; lm_model1
# напомнию, что точка означает, что именно в этом месте нужно передать в функцию данные
# полученные на предыдущей строчке пайпа. Посмотрите структуру функции lm() в справке, 
# на этом находится аргумент `data = `
lm_model1</code></pre>
<pre><code>## 
## Call:
## lm(formula = Life_Ladder ~ Log_GDP_per_capita, data = .)
## 
## Coefficients:
##        (Intercept)  Log_GDP_per_capita  
##            -1.4066              0.7421</code></pre>
<pre><code>summary(lm_model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Life_Ladder ~ Log_GDP_per_capita, data = .)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.26515 -0.47805 -0.04913  0.54993  2.01866 
## 
## Coefficients:
##                    Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)         -1.4066     0.1467  -9.587 &lt;0.0000000000000002 ***
## Log_GDP_per_capita   0.7421     0.0158  46.973 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7016 on 1404 degrees of freedom
##   (15 observations deleted due to missingness)
## Multiple R-squared:  0.6111, Adjusted R-squared:  0.6109 
## F-statistic:  2206 on 1 and 1404 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<pre><code>anova(lm_model1)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Life_Ladder
##                      Df  Sum Sq Mean Sq F value                Pr(&gt;F)    
## Log_GDP_per_capita    1 1086.07 1086.07  2206.5 &lt; 0.00000000000000022 ***
## Residuals          1404  691.07    0.49                                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<pre><code># options(scipen = 999) функция, которая отключает нотацию записи чисел через экспоненту</code></pre>
<p>In general, we can already begin to interpret the results of the model, but it is still too early - first we need to make sure that the variances of the residuals are equal, that is, that the assumption of <em>homoscedasticity</em> (homogeneity) of the variances is met. This is easiest to check by displaying the first of four graphs that are displayed if you pass the linear model to the basic plot() function.</p>
<pre><code>plot(lm_model1, 1)</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-84-1.png" class="img-fluid"></p>
<p>We can make the graph prettier using ggplot(). To do this, we will use the fact that the result of executing lm() is a list containing many different data, including both the model residuals and the predicted values ​​separately.</p>
<pre><code>head(lm_model1$residuals) #head() выводит заголовок, первые элементы</code></pre>
<pre><code>##         1         2         3         4         5         6 
## 0.9974072 1.4818864 1.2677150 1.4125433 1.1663137 1.2430108</code></pre>
<pre><code>head(lm_model1$fitted.values)</code></pre>
<pre><code>##        1        2        3        4        5        6 
## 6.560375 6.537048 6.566518 6.558349 6.517045 6.527505</code></pre>
<pre><code>ggplot(lm_model1, aes(x = lm_model1$fitted.values, y = lm_model1$residuals)) +
  geom_point(color = "#355C7D", size = 1) +
  theme_minimal()</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-86-1.png" class="img-fluid"> Let’s recall the examples of diagnostic graphs that we discussed last semester Examples of diagnostic graphs for residuals: <a href="https://gallery.shinyapps.io/slr_diag/" class="uri">https://gallery.shinyapps.io/slr_diag/</a> A graph is considered good if, when moving from left to right, all the points are distributed approximately evenly. But if we have a broom, that on one side the data has shrunk to one point, and then they start to diverge like a broom - this means that <em>heteroscedasticity</em> is observed in the data , they are not homogeneous, and the results of such a model will not be very reliable. In our case, the graph looks good and passes the test.</p>
<p>Now let’s take an anti-example and see what happens to the distribution of the residuals.</p>
<pre><code>whr_tests_hw %&gt;% 
  lm(Life_Ladder ~ Perceptions_of_corruption, .) -&gt; lm_model2_anti
plot(lm_model2_anti, 1)</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-87-1.png" class="img-fluid"></p>
<p>Something went wrong here, so we wouldn’t rely on such a model.</p>
<p>The next assumption is that the residuals must be normally distributed. Yes, we do not check for normality of the PP distribution, but the residuals need to be checked - otherwise we will not be able to draw a line with the least squares method calculation, that is, trying to get closer to all our points at once. Let’s check this assumption by displaying the second graph of the standard plot() function.</p>
<pre><code>plot(lm_model1, 2)</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-88-1.png" class="img-fluid"> Or, as we have already built beautiful graphs to check normality using ggplot</p>
<pre><code>ggplot(data = lm_model1, aes(x = lm_model1$residuals)) +
  geom_density(color = "#355C7D") +
  theme_minimal()</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-89-1.png" class="img-fluid"></p>
<pre><code>ggplot(data = lm_model1, aes(sample = lm_model1$residuals)) +
  stat_qq(color = "#355C7D") +
  geom_qq_line() +
  theme_minimal()</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-89-2.png" class="img-fluid"></p>
<p>So, we have met all the assumptions for the single predictor model! We only have the assumption of no multicollinearity left, but it is not applicable to the single predictor model.</p>
<p>Now let’s look again at the model results and remember <a href="https://elenary.github.io/StatsForDA/stats_criteria_linear.html#linreg_example">how to interpret them</a> . The key thing we are interested in is <a href="https://elenary.github.io/StatsForDA/stats_criteria_linear.html#linreg_coef">the linear regression coefficients</a> ,b0b0, intercept, the intersection of the regression line with the y-axis, andb1b1, slope, the angle of inclination of the line - since <a href="https://elenary.github.io/StatsForDA/stats_criteria_linear.html#linreg_null">the null hypothesis for linear regression</a> is that they are equal to zero. Another equally important thing isR2R2, <a href="https://elenary.github.io/StatsForDA/stats_criteria_linear.html#rsquared">the coefficient of determination and the percentage of explained variance</a> .</p>
<pre><code>lm_model1</code></pre>
<pre><code>## 
## Call:
## lm(formula = Life_Ladder ~ Log_GDP_per_capita, data = .)
## 
## Coefficients:
##        (Intercept)  Log_GDP_per_capita  
##            -1.4066              0.7421</code></pre>
<pre><code>summary(lm_model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Life_Ladder ~ Log_GDP_per_capita, data = .)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.26515 -0.47805 -0.04913  0.54993  2.01866 
## 
## Coefficients:
##                    Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept)         -1.4066     0.1467  -9.587 &lt;0.0000000000000002 ***
## Log_GDP_per_capita   0.7421     0.0158  46.973 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7016 on 1404 degrees of freedom
##   (15 observations deleted due to missingness)
## Multiple R-squared:  0.6111, Adjusted R-squared:  0.6109 
## F-statistic:  2206 on 1 and 1404 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>As usual, we look at the p-value of each coefficient (and we can also look at the p-value of the entire model: here the same story as with ANOVA - the entire model is significant when at least one of the coefficients is significant, and is not significant when all coefficients do not differ statistically significantly from zero). If the coefficient is significant, then we can say that it significantly contributes to the explanation of the variance.b0b0, the intercept, is significantly different from zero, so we can say that our line will not start at the origin, but will be shifted by -1.4 along the y-axis.b1b1Log_GDP_per_capita is significantly different from zero, so our line will have a slope - which means that with an increase in Log_GDP_per_capita by 1, the dependent variable Life_Ladder will increase by 0.74!</p>
<p>What is it equal to?R2R2? It is equal to 0.61, which is a very good result. That is, 61% of the variability of our data at the Life_Ladder level is determined by the level of purchasing power Log_GDP_per_capita!</p>
<p>I can now write the equation of the regression line as follows:</p>
<p><sup>Lifand_Laddandr=−1.4+0.74×Ltheg_GDP_pandr_capitaL</sup>ifand_Laddandr=−1.4+0.74×Ltheg_GDP_pandr_capita</p>
<p>Let’s now visualize our regression line</p>
<pre><code>whr_tests_hw %&gt;% 
  ggplot(aes(x = Log_GDP_per_capita, y = Life_Ladder)) +
  geom_point(color = "#355C7D", size = 1, alpha = 0.5) +
  geom_smooth(method = 'lm', color = "violet") +
  theme_minimal()</code></pre>
<pre><code>## Warning: Removed 15 rows containing non-finite values (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 15 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-91-1.png" class="img-fluid"></p>
<p>Beauty!</p>
</section>
<section id="linear-regression-with-multiple-predictors-factors" class="level3" data-number="14.2.2">
<h3 data-number="14.2.2" class="anchored" data-anchor-id="linear-regression-with-multiple-predictors-factors"><span class="header-section-number">14.2.2</span> 14.15.2 Linear Regression with Multiple Predictors (Factors)</h3>
<p>Everything is the same, but now we will take the second predictor into the model – Freedom_to_make_life_choices.</p>
<pre><code>whr_tests_hw %&gt;%
  lm(Life_Ladder ~ Log_GDP_per_capita + Freedom_to_make_life_choices, .) -&gt; lm_model3_multy
lm_model3_multy</code></pre>
<pre><code>## 
## Call:
## lm(formula = Life_Ladder ~ Log_GDP_per_capita + Freedom_to_make_life_choices, 
##     data = .)
## 
## Coefficients:
##                  (Intercept)            Log_GDP_per_capita  
##                      -2.0948                        0.6478  
## Freedom_to_make_life_choices  
##                       2.1544</code></pre>
<pre><code>summary(lm_model3_multy)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Life_Ladder ~ Log_GDP_per_capita + Freedom_to_make_life_choices, 
##     data = .)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.50100 -0.43131  0.02093  0.44158  1.83176 
## 
## Coefficients:
##                              Estimate Std. Error t value            Pr(&gt;|t|)
## (Intercept)                  -2.09478    0.14063  -14.90 &lt;0.0000000000000002
## Log_GDP_per_capita            0.64781    0.01562   41.46 &lt;0.0000000000000002
## Freedom_to_make_life_choices  2.15438    0.12663   17.01 &lt;0.0000000000000002
##                                 
## (Intercept)                  ***
## Log_GDP_per_capita           ***
## Freedom_to_make_life_choices ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.6403 on 1375 degrees of freedom
##   (43 observations deleted due to missingness)
## Multiple R-squared:  0.6791, Adjusted R-squared:  0.6787 
## F-statistic:  1455 on 2 and 1375 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>Checking is allowed</p>
<pre><code>plot(lm_model3_multy, 1)</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-93-1.png" class="img-fluid"></p>
<pre><code>plot(lm_model3_multy, 2)</code></pre>
<p><img src="https://elenary.github.io/StatsForDA/StatsForDA_files/figure-html/unnamed-chunk-93-2.png" class="img-fluid"></p>
<p>Now we need to check the assumption about the absence of multicollinearity - that there is no strong correlation between the predictors (NP), otherwise our model will be a bit meaningless. We will check using the vif() function, the dispersion inflation coefficient. The indicators are quite arbitrary, but it is considered that if the values ​​are greater than 5, then this is a very strong correlation between the variables, and the strongly correlated variable should be removed.</p>
<pre><code>car::vif(lm_model3_multy)</code></pre>
<pre><code>##           Log_GDP_per_capita Freedom_to_make_life_choices 
##                     1.153419                     1.153419</code></pre>
<p>Our vif readings are quite low, so we won’t change anything.</p>
<p>Next we can interpret the results (all coefficients are significant) and write down the equation of the regression line.</p>
<p><sup>Lifand_Laddandr=−2.09+0.64×Ltheg_GDP_pandr_capita+2.15×Frandanddthem_tthe_makand_lifand_chtheicandsL</sup>ifand_Laddandr=−2.09+0.64×Ltheg_GDP_pandr_capita+2.15×Frandanddthem_tthe_makand_lifand_chtheicands</p>
</section>
</section>
<section id="assignments-after-the-seminar-7" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="assignments-after-the-seminar-7"><span class="header-section-number">14.3</span> 14.16 Assignments after the seminar 7</h2>
<ol type="1">
<li><p>Select variables suitable for linear regression in the data<code>whr_tests_hw.csv</code></p></li>
<li><p>Construct a linear regression on these variables, with one factor (LF)</p></li>
<li><p>Construct a linear regression on these variables, but with at least two factors (NP)</p></li>
<li><p>Plot diagnostic plots for each model: how equal is the variance of the residuals for these models? Can we trust the results of these models?</p></li>
<li><p>Determine which model best explains the data (i.e.&nbsp;wage variability)?</p></li>
<li><p>Write the linear regression equation for both models.</p></li>
</ol>
</section>
<section id="logistic-regression" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">14.4</span> 14.17 Logistic Regression</h2>
<p>Let’s move from linear regression to <a href="https://elenary.github.io/StatsForDA/stats_criteria_categ.html#logreg">logistic</a> regression. First, let’s remember what this method is and when it is used - it is used when the salary is not quantitative, but categorical, and, as a rule, has two gradations. This is the most classic case of logistic regression, although the salary in it can have more gradations than two - then it will be <em>a multinomial logistic regression</em> . All machine learning is built on log regression - tasks in which it is necessary to determine whether an image belongs to a certain pattern (for example, text recognition), whether a credit borrower is reliable for issuing a loan (scoring models in banks), etc. use this method.</p>
<p>We will consider it on the same example of our data from the World Happiness Report. They are not very suitable for this method, so the task will be a bit artificial - we will try to predict whether a country will be in the first or second half of the rating by level of happiness (we created a special variable for this). First, I will recode this variable into 1 and 0, since log regression works with numerical values ​​0 and 1.</p>
<pre><code>whr_tests_hw %&gt;%
  mutate(mean_position_bi = ifelse(mean_position == "upper", 1, 0)) -&gt; whr_tests_hw</code></pre>
<p>First, let’s build the simplest model, which will include only the intercept. This model is essentially an analogue of chi-square - without any predictors, estimate whether a country will be in the first or second half of the rating, purely based on the frequency of occurrence of countries from the first and second halves? Specifically, in this example, the frequencies will be approximately the same, but the principle of operation of this model is approximately the same.</p>
<pre><code>table(whr_tests_hw$mean_position)</code></pre>
<pre><code>## 
## lower upper 
##    78    75</code></pre>
<pre><code>whr_tests_hw %&gt;%
  glm(mean_position_bi ~ 1, data = ., family = binomial) -&gt; lm_model_log1
summary(lm_model_log1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = mean_position_bi ~ 1, family = binomial, data = .)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.161  -1.161  -1.161   1.194   1.194  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -0.03922    0.16172  -0.243    0.808
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 212.04  on 152  degrees of freedom
## Residual deviance: 212.04  on 152  degrees of freedom
##   (1268 observations deleted due to missingness)
## AIC: 214.04
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<pre><code>log(75/78)</code></pre>
<pre><code>## [1] -0.03922071</code></pre>
<pre><code># log(p/1-p) = intercept</code></pre>
<p>Let’s complicate the model and add GDP per capita as a predictor</p>
<pre><code>whr_tests_hw %&gt;%
  glm(mean_position_bi ~ Log_GDP_per_capita, ., family = binomial) -&gt; lm_model_log2
summary(lm_model_log2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = mean_position_bi ~ Log_GDP_per_capita, family = binomial, 
##     data = .)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9946  -0.4687  -0.0601   0.5165   2.1031  
## 
## Coefficients:
##                    Estimate Std. Error z value       Pr(&gt;|z|)    
## (Intercept)        -21.8266     3.5703  -6.113 0.000000000976 ***
## Log_GDP_per_capita   2.3186     0.3758   6.169 0.000000000685 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 207.84  on 149  degrees of freedom
## Residual deviance: 109.90  on 148  degrees of freedom
##   (1271 observations deleted due to missingness)
## AIC: 113.9
## 
## Number of Fisher Scoring iterations: 6</code></pre>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./r_4.html" class="pagination-link" aria-label="Testing hypotheses">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Testing hypotheses</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>